name: indicafacil_admin_web
description: IndicaFácil Admin Web - painel administrativo em Flutter Web
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mask_text_input_formatter: ^2.9.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true